# yum-config-manager --enable epel

# sudo yum install -y bison cmake3 ethtool flex git iperf libstdc++-static python-netaddr gcc gcc-c++ make zlib-devel elfutils-libelf-devel
# sudo yum install -y luajit luajit-devel
# sudo yum install -y http://repo.iovisor.org/yum/extra/mageia/cauldron/x86_64/netperf-2.7.0-1.mga6.x86_64.rpm
# sudo pip install pyroute2
# sudo yum install -y ncurses-devel

# from https://github.com/iovisor/bpftrace/blob/master/INSTALL.md#amazon-linux
---
- name: install bpftrace
  hosts: all
  connection: ssh
  become: yes
  become_user: root
  become_method: sudo

  tasks:
  - name: 'Install epel'
    become: yes
    command: sudo amazon-linux-extras install epel -y
  
  - name: 'Install pip'
    become: yes
    command: yum install python-pip -y 

  - name: 'Install bpftrace dependencies'
    yum: name={{item}} state=latest
    with_items:
      - 'bison'
      - 'cmake3'
      - 'ethtool'
      - 'flex'
      - 'git'
      - 'iperf'
      - 'libstdc++-static'
      - 'python-netaddr'
      - 'gcc'
      - 'gcc-c++'
      - 'make'
      - 'zlib-devel'
      - 'elfutils-libelf-devel'
      - 'clang'
      - 'bcc-devel'

  - name: 'Install pyroute2'
    become: yes
    command: pip install pyroute2

  - name: 'Install ncurses-devel'
    become: yes
    command: yum install -y ncurses-devel


  - name: 'clone bpftrace repository'
    git:
      repo: 'https://github.com/iovisor/bpftrace'
      dest: '/usr/share/bpftrace'
      force: 'yes'

  - name: 'create build directory'
    file:
      path: '/usr/share/bpftrace/build'
      state: 'directory'
      mode: 0755

  - name: 'prepare makefile'
    command: 'cmake3 -DCMAKE_BUILD_TYPE=RELEASE ..'
    args:
      chdir: '/usr/share/bpftrace/build'

  - name: 'build'
    command: 'make -j8'
    args:
      chdir: '/usr/share/bpftrace/build'

  - name: 'install'
    command: 'make -j8'
    args:
      chdir: '/usr/share/bpftrace/build'


# sudo bash
# builddir=/media/ephemeral0	# change to suit your system: needs about 2 Gbytes free

# # dependencies
# yum install git cmake3 gcc64-c++.x86_64 bison flex

# # llvm
# cd $builddir
# wget http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-linux-gnu-Fedora27.tar.xz
# tar xf clang*
# (cd clang* && sudo cp -R * /usr/local/)
# cp -p /usr/lib64/llvm6.0/lib/libLLVM-6.0.so /usr/lib64/libLLVM.so

# # libtinfo.so.6 (comes from ncurses)
# cd $builddir
# wget ftp://ftp.gnu.org/gnu/ncurses/ncurses-6.0.tar.gz
# tar xvf ncurses-6.0.tar.gz
# cd ncurses-6.0
# ./configure --with-shared --with-termlib
# make -j8
# make install

# # bison
# cd $builddir
# wget http://ftp.gnu.org/gnu/bison/bison-3.1.tar.gz
# tar xf bison*
# cd bison*
# ./configure
# make -j4
# make install

# # bpftrace
# cd $builddir
# git clone https://github.com/iovisor/bpftrace
# cd bpftrace
# mkdir build; cd build
# cmake3 ..
# make -j8
# make install
# echo /usr/local/lib >> /etc/ld.so.conf
# ldconfig -v


# - name: 'clone bpftrace repository'
#   git:
#     repo: 'https://github.com/iovisor/bpftrace'
#     dest: '/usr/share/bpftrace'
#     force: 'yes'

# - name: 'create build directory'
#   file:
#     path: '/usr/share/bpftrace/build'
#     state: 'directory'
#     mode: 0755

# - name: 'prepare makefile'
#   command: 'cmake -DCMAKE_BUILD_TYPE=DEBUG ..'
#   args:
#     chdir: '/usr/share/bpftrace/build'

# - name: 'build'
#   command: 'make -j3'
#   args:
#     chdir: '/usr/share/bpftrace/build'

# - name: 'install'
#   command: 'make -j3'
#   args:
#     chdir: '/usr/share/bpftrace/build'

