---
    
- name: Configure EC2 instance
  hosts: all
  connection: ssh
  become: yes
  become_user: root
  become_method: sudo

  tasks:
  - name: Update the machine
    command: yum update -y
    
  - name: Installing essentials
    become: yes
    command: yum install yum-utils wget -y

  - name: Installing epel
    become: yes
    command: sudo amazon-linux-extras install epel -y 
  
  - name: Installing git
    become: yes
    command: yum install git -y

  - name: Installing autogen
    become: yes
    command: yum install autogen -y

  - name: Installing gcc
    become: yes
    command: yum install gcc -y

  - name: Installing numactl
    become: yes
    command: yum install numactl -y

  - name: Installing htop
    become: yes
    command: yum install htop -y

  - name: Installing NUMAD
    become: yes
    command: yum install numad -y
      
    
