---    
- hosts: all
  connection: ssh
  become: yes
  become_user: root
  become_method: sudo
  roles:
  - cloudalchemy.node-exporter
  vars:
    - node_exporter_enabled_collectors:
      - systemd
      - textfile
      - interrupts
      - meminfo_numa
      - processes