---
- name: Install aibench
  hosts: all
  connection: ssh
  become: yes
  become_user: root
  become_method: sudo
  vars:
    aibench_root_dir: $GOPATH/src/github.com/RedisAI/aibench
  tasks:
  - name: go get github.com/RedisAI/aibench
    become: yes
    command: go get -v github.com/RedisAI/aibench/...

  - name: Go install aibench aibench_generate_data
    become: yes
    command: go install github.com/RedisAI/aibench/cmd/aibench_generate_data

  - name: Go install aibench aibench_load_data
    become: yes
    command: go install github.com/RedisAI/aibench/cmd/aibench_load_data

  - name: Go install aibench aibench_run_inference_redisai
    become: yes
    command: go install github.com/RedisAI/aibench/cmd/aibench_run_inference_redisai

  - name: Go install aibench aibench_run_inference_tensorflow_serving
    become: yes
    command: go install github.com/RedisAI/aibench/cmd/aibench_run_inference_tensorflow_serving

  - name: Go install aibench aibench_run_inference_flask_tensorflow
    become: yes
    command: go install github.com/RedisAI/aibench/cmd/aibench_run_inference_flask_tensorflow



  