---
- name: Install golang
  hosts: all
  connection: ssh
  become: yes
  become_user: root
  become_method: sudo 
  tasks:
  
  ### ubuntu

  - name: add-apt-repository ppa:longsleep/golang-backports
    become: yes
    command: add-apt-repository ppa:longsleep/golang-backports -y
    when: 
      - ansible_distribution_release == 'xenial' or ansible_distribution_release == 'trusty'

  - name: Install golang-go
    become: yes
    apt: 
      name: golang-go
      state: latest
      update_cache: yes
    when: 
      - ansible_distribution_release == 'xenial' or ansible_distribution_release == 'trusty'

  - name: Add latest Go repository s1
    become: yes
    command: rpm --import https://mirror.go-repo.io/centos/RPM-GPG-KEY-GO-REPO 
    when: 
      - ansible_os_family == 'RedHat'
  
  ### rhel7

  - name: Add repository
    become: yes
    yum_repository:
      name: "go-repo"
      description: go-repo
      file: external_repos
      baseurl: https://mirror.go-repo.io/centos/7/$basearch/
      gpgkey: https://mirror.go-repo.io/centos/RPM-GPG-KEY-GO-REPO
      gpgcheck: no
      # state: absent

    when: 
      - ansible_os_family == 'RedHat'

  - name: Install golang
    become: yes
    command: sudo yum install golang -y

    when: 
      - ansible_os_family == 'RedHat'

  - name: update golang
    become: yes
    command: sudo yum update golang --disableplugin=priorities -y

    when: 
      - ansible_os_family == 'RedHat'

  ### common

  - name: modify .bashrc
    become: yes
    blockinfile:
      dest: "~/.bashrc"
      block: |
        export GOPATH=$HOME/go
        export GOBIN=$GOPATH/bin
        export PATH=$GOBIN:$PATH:/usr/local/go/bin
      marker: '# {mark} ANSIBLE MANAGED BLOCK - changes for golang'
      insertafter: EOF
      create: yes 