---    
- name: Install netdata
  hosts: all
  connection: ssh
  become: yes
  become_user: root
  become_method: sudo
  vars:
    - netdata_history: 86400
    - netdata_default_port: 49999
  roles:
  - mrlesmithjr.netdata