---    
- name: Install netdata
  hosts: all
  connection: ssh
  become: yes
  become_user: root
  become_method: sudo
  roles:
  - jffz.netdata

  tasks:
  - name: Ensure the default Port is set to 49999
    lineinfile:
      path: /etc/netdata/netdata.conf
      regexp: '# default port = 19999'
      line: default port = 49999

  - name: Ensure retention period is set to 86400 seconds ( 1 day )
    lineinfile:
      path: /etc/netdata/netdata.conf
      regexp: '# history = 3600'
      line: history = 86400