---
- name: Install TigerGraph's graph-database-benchmark
  hosts: all
  connection: ssh
  become: yes
  become_user: root
  become_method: sudo
  vars:
    tigergraph_bulk_data_dir: /root/bulk_data
    tigergraph_root_dir: /root/graph-database-benchmark
    tigergraph_build_dir: "{{ tigergraph_root_dir }}/benchmark/redisgraph"
    tigergraph_version: "perf"
    
  pre_tasks:
    - name: Prepare system
      become: yes
      shell: apt-get install python python3-pip -y
      args:
        executable: /bin/bash
      when:
        - ansible_distribution == 'Ubuntu'

  tasks:
  - name: clone graph-database-benchmark git repo
    git:
      repo: https://github.com/RedisGraph/graph-database-benchmark.git
      dest: "{{ tigergraph_root_dir }}"
      version: "{{ tigergraph_version }}"

  - name: install the benchmark
    command: python3 -m pip install --user -r requirements.txt
    args:
      chdir: "{{ tigergraph_build_dir }}"

  - name: retrieve graph500 dataset
    command: BULK_DATA_DIR={{ tigergraph_bulk_data_dir }} ./scripts/get_graph500_dataset.sh
    args:
      chdir: "{{ tigergraph_build_dir }}"