---
- name: Install aibench
  hosts: all
  connection: ssh
  become: yes
  become_user: root
  become_method: sudo
  vars:
    aibench_root_dir: $GOPATH/src/github.com/RedisAI/aibench
  tasks:
  - name: add-apt-repository ppa:longsleep/golang-backports
    become: yes
    command: add-apt-repository ppa:longsleep/golang-backports -y

  - name: Install golang-go
    become: yes
    apt: 
      name: golang-go
      state: latest
      update_cache: yes

  - name: modify .bashrc
    become: yes
    blockinfile:
      dest: "~/.bashrc"
      block: |
        export GOPATH=$HOME/go
        export GOBIN=$GOPATH/bin
        export PATH=$GOBIN:$PATH:/usr/local/go/bin
      marker: '# {mark} ANSIBLE MANAGED BLOCK - changes for golang'
      insertafter: EOF
      create: yes 

  - name: Go install aibench aibench_generate_data
    become: yes
    command: go install github.com/RedisAI/aibench/cmd/aibench_generate_data

  - name: Go install aibench aibench_load_data
    become: yes
    command: go install github.com/RedisAI/aibench/cmd/aibench_load_data

  - name: Go install aibench aibench_run_inference_redisai
    become: yes
    command: go install github.com/RedisAI/aibench/cmd/aibench_run_inference_redisai

  - name: Go install aibench aibench_run_inference_tensorflow_serving
    become: yes
    command: go install github.com/RedisAI/aibench/cmd/aibench_run_inference_tensorflow_serving

  - name: Go install aibench aibench_run_inference_flask_tensorflow
    become: yes
    command: go install github.com/RedisAI/aibench/cmd/aibench_run_inference_flask_tensorflow



  