---
    
- name: Configure EC2 instance
  hosts: all
  connection: ssh
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Install normal required packages
      # become: yes
      apt:
        pkg:
        - git
        - autogen
        - gcc
        - make
        - numactl
        - htop
      
    
