- hosts: all
  roles:
    - role: cloudalchemy.grafana
      vars:
        grafana_security:
          admin_user: admin
          admin_password: "{{ lookup('env','GRAFANA_PASSWORD') }}"
        grafana_datasources:
          - name: prometheus
            type: prometheus
            access: proxy
            url: 'http://{{ prometheus_web_listen_address }}'
            basicAuth: false