---    
- name: Install memtier
  hosts: all
  connection: ssh
  become: yes
  become_user: root
  become_method: sudo
 
  vars:
    installdir: /usr/bin/

  tasks:
  - name: install 
    command: apt-get install build-essential autoconf automake libpcre3-dev libevent-dev pkg-config zlib1g-dev libssl-dev -y

  - name: 'clone Memtier repository'
    git:
      repo: 'https://github.com/filipecosta90/memtier_benchmark'
      dest: '{{installdir}}/memtier_benchmark'
      version: 'hdr.hist'
      force: 'yes'

  - name: autoreconf
    command: autoreconf -ivf chdir={{installdir}}/memtier_benchmark/

  - name: configure
    command: ./configure chdir={{installdir}}/memtier_benchmark/

  - name: make
    command: make chdir={{installdir}}/memtier_benchmark/

  - name: install 
    command: make install chdir={{installdir}}/memtier_benchmark/
  
  pre_tasks:

  - name: Wait for /var/lib/dpkg/lock
    become: yes
    shell:  while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

  - name: Wait for /var/lib/dpkg/lock-frontend
    become: yes
    shell:  while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 5; done;

  - name: Remove apt lock file
    become: yes
    file:
      state: absent
      path: "/var/lib/dpkg/lock"

  - name: Remove apt lock frontend file
    become: yes
    file:
      state: absent
      path: "/var/lib/dpkg/lock-frontend"


    