---
- name: Install RedisGraph OSS version 
  hosts: all
  connection: ssh
  become: yes
  become_user: root
  become_method: sudo
  vars:
    redisgraph_root_dir: /root/RedisGraph
    redisgraph_build_dir: /root/RedisGraph
    redisgraph_version: "{{ redisgraph_version | default('master') }}"

  tasks:
  - name: Update
    become: yes
    command: apt update -y

  - name: Install normal required packages
    become: yes
    command: apt install build-essential cmake m4 automake peg libtool autoconf -y
  
  - name: clone RedisGraph git repo
    git:
      repo: https://github.com/RedisGraph/RedisGraph.git
      dest: "{{ redisgraph_root_dir }}"
      version: "{{ redisgraph_version }}"
      recursive: yes
      track_submodules: yes
      force: yes

  - name: compile RedisGraph dependencies with normal optimizations
    become: yes
    command: make
    args:
      chdir: "{{ redisgraph_build_dir }}"

  - name: copy redis.conf
    template:
      src: oss_redis_redisgraph.conf.j2
      dest: "{{ redisgraph_build_dir }}/redis.conf"

  - name: start redis-server with redisgraph binded to core 1
    become: yes
    command: OMP_NUM_THREADS={{ OMP_NUM_THREADS }} /usr/local/bin/redis-server {{ redisgraph_build_dir }}/redis.conf
    args:
      chdir: "{{ redisgraph_build_dir }}"
