---
- name: Install TensorFlow Serving
  hosts: all
  connection: ssh
  become: yes
  become_user: root
  become_method: sudo
  # gather_facts: false
  tasks:
    
  # Add TensorFlow Serving distribution URI as a package source
  # - name: Add TensorFlow Serving distribution URI as a package source
  #   become: yes
  #   apt_repository:    
  #     repo: deb [arch=amd64] http://storage.googleapis.com/tensorflow-serving-apt stable tensorflow-model-server tensorflow-model-server-universal
  #     state: present

  # - name: Run the equivalent of "apt-get update" as a separate step
  #   become: yes
  #   apt:
  #     update_cache: yes

  - name: Add TensorFlow Serving distribution URI as a package source
    become: yes
    command: echo "deb [arch=amd64] http://storage.googleapis.com/tensorflow-serving-apt stable tensorflow-model-server tensorflow-model-server-universal" | sudo tee /etc/apt/sources.list.d/tensorflow-serving.list 

  # - name: Add TensorFlow Serving distribution URI as a package source
  #   become: yes
  #   command: curl https://storage.googleapis.com/tensorflow-serving-apt/tensorflow-serving.release.pub.gpg | sudo apt-key add -

  - name: Add TensorFlow Serving distribution URI as a package source
    become: yes
    command: apt-get update --allow-unauthenticated

  - name: Add TensorFlow Serving distribution URI as a package source
    become: yes
    command: apt-get install --allow-unauthenticated tensorflow-model-server -y

  - name: Add TensorFlow Serving distribution URI as a package source
    become: yes
    command: apt-get upgrade --allow-unauthenticated tensorflow-model-server -y

  # - name: Install TensorFlow ModelServer
  #   become: yes
  #   apt: 
  #     name: tensorflow-model-server
  #     state: latest
  #     # update_cache: yes
  #     allow_unauthenticated: yes

  